GET http://localhost:3000/sensatta HTTP/1.1
content-type: application/json
### 

POST http://localhost:3000/sensatta/sync/invoice HTTP/1.1
content-type: application/json 
### 

POST http://localhost:3000/sensatta/sync/inventory HTTP/1.1
content-type: application/json 
### 

POST http://localhost:3000/sensatta/sync/sync-with-storage HTTP/1.1
content-type: application/json 
### 

GET http://localhost:3000/health HTTP/1.1
content-type: application/json
###

GET http://localhost:3000/test HTTP/1.1
content-type: application/json
### 

POST http://localhost:3000/sensatta/sync HTTP/1.1
content-type: application/json 
###

POST http://localhost:3000/sensatta/sync/invoice HTTP/1.1
content-type: application/json 
###

POST http://localhost:3000/sensatta/sync/stock HTTP/1.1
content-type: application/json 
###

POST http://localhost:3000/sensatta/sync/freights HTTP/1.1
content-type: application/json 
###

POST http://localhost:3000/sensatta/sync/purchase HTTP/1.1
content-type: application/json 
###

POST http://localhost:3000/sensatta/sync/finance HTTP/1.1
content-type: application/json 
###
POST http://localhost:3000/temp/sync HTTP/1.1
content-type: application/json 
###