export interface AccountReceivableSyncRequestInput {
  DT_BASE: string;
  SEQUENCIAL_TITULO_RECEBER: string;
  ESPECIE_TITULO: string;
  ORIGEM: string;
  CHAVE: string;
  CODIGO_EMPRESA: string;
  NUMERO_TITULO: string;
  DATA_EMISSAO: Date;
  DATA_VENCIMENTO: Date;
  DATA_BAIXA: Date;
  DATA_BAIXA_PERDA: Date;
  SITUACAO: string;
  CODIGO_CLIENTE: number;
  CLIENTE: string;
  CODIGO_REPRESENTANTE: string;
  REPRESENTANTE: string;
  ID_ESPECIE_COBRANCA: string;
  ESPECIE_COBRANCA: string;
  SEQUENCIAL_NOTA_SAIDA: string;
  NOTA_SAIDA: string;
  CODIGO_CFOP: string;
  DESCRICAO_CFOP: string;
  CONTA_CONTABIL: string;
  CLASSIFICACAO_CONTABIL: string;
  NOME_CONTA_CONTABIL: string;
  TIPO_PESSOA: string;
  MOEDA: string;
  VALOR: number;
  VALOR_ABERTO: number;
  USUARIO_CRIACAO: string;
  USUARIO_APROVACAO: string;
  OBSERVACAO: string;
}
export class AccountReceivableSyncRequestDto {
  baseDate?: Date;
  sensattaId?: string;
  key?: string;
  companyCode?: string;
  receivableNumber?: string;
  issueDate?: Date;
  dueDate?: Date;
  recognitionDate?: Date;
  lossRecognitionDate?: Date;
  status?: string;
  clientCode?: string;
  clientName?: string;
  salesRepresentativeCode?: string;
  salesRepresentativeName?: string;
  nfId?: string;
  nfNumber?: string;
  cfopCode?: string;
  cfopDescription?: string;
  accountingAccount?: string;
  accountingClassification?: string;
  accountingAccountName?: string;
  type?: string;
  originType?: string;
  billingTypeId?: string;
  billingType?: string;
  personType?: string;
  currency?: string;
  value?: number;
  openValue?: number;
  sensattaCreatedBy?: string;
  sensattaApprovedBy?: string;
  observation?: string;

  constructor(data: AccountReceivableSyncRequestInput) {
    Object.assign(this, {
      baseDate: data.DT_BASE,
      sensattaId: data.SEQUENCIAL_TITULO_RECEBER,
      key: data.CHAVE,
      companyCode: data.CODIGO_EMPRESA,
      receivableNumber: data.NUMERO_TITULO,
      issueDate: data.DATA_EMISSAO,
      dueDate: data.DATA_VENCIMENTO,
      recognitionDate: data.DATA_BAIXA,
      lossRecognitionDate: data.DATA_BAIXA_PERDA,
      status: data.SITUACAO,
      clientCode: data.CODIGO_CLIENTE,
      clientName: data.CLIENTE,
      salesRepresentativeCode: data.CODIGO_REPRESENTANTE,
      salesRepresentativeName: data.REPRESENTANTE,
      nfId: data.SEQUENCIAL_NOTA_SAIDA,
      nfNumber: data.NOTA_SAIDA,
      cfopCode: data.CODIGO_CFOP,
      cfopDescription: data.DESCRICAO_CFOP,
      accountingAccount: data.CONTA_CONTABIL,
      accountingClassification: data.CLASSIFICACAO_CONTABIL,
      accountingAccountName: data.NOME_CONTA_CONTABIL,
      type: data.ESPECIE_TITULO,
      originType: data.ORIGEM,
      billingTypeId: data.ID_ESPECIE_COBRANCA,
      billingType: data.ESPECIE_COBRANCA,
      personType: data.TIPO_PESSOA,
      currency: data.MOEDA,
      value: data.VALOR,
      openValue: data.VALOR_ABERTO,
      sensattaCreatedBy: data.USUARIO_CRIACAO,
      sensattaApprovedBy: data.USUARIO_APROVACAO,
      observation: data.OBSERVACAO,
    });
  }
}
