export interface AccountPayableSyncRequestInput {
  DT_BASE: string;
  SEQUENCIAL_TITULO_PAGAR: string;
  CHAVE: string;
  CODIGO_EMPRESA: string;
  NUMERO_TITULO: string;
  DATA_EMISSAO: Date;
  DATA_VENCIMENTO: Date;
  DATA_LIQUIDACAO: Date;
  SITUACAO: string;
  CODIGO_FORNECEDOR: number;
  FORNECEDOR: string;
  CODIGO_TIPO_BAIXA: string;
  TIPO_BAIXA: string;
  CONTA_CONTABIL: string;
  CLASSIFICACAO_CONTABIL: string;
  NOME_CONTA_CONTABIL: string;
  CODIGO_CLIENTE: string;
  CLIENTE: string;
  CODIGO_REPRESENTANTE: string;
  REPRESENTANTE: string;
  SEQUENCIAL_NOTA_ENTRADA: string;
  NOTA_FISCAL: string;
  CODIGO_CFOP: string;
  DESCRICAO_CFOP: string;
  MOEDA: string;
  VALOR_BRUTO: number;
  VALOR_PAGO: number;
  ACRESCIMO: number;
  USUARIO_CRIACAO: string;
  USUARIO_VISTO: string;
  USUARIO_APROVACAO: string;
  USUARIO_LIQUIDACAO: string;
  OBSERVACAO: string;
}
export class AccountPayableSyncRequestDto {
  baseDate?: Date;
  sensattaId?: string;
  key?: string;
  companyCode?: string;
  paymentNumber?: string;
  issueDate?: Date;
  dueDate?: Date;
  liquidationDate?: Date;
  status?: string;
  supplyCode?: string;
  supplyName?: string;
  recognitionTypeCode?: string;
  recognitionType?: string;
  accountingAccount?: string;
  accountingClassification?: string;
  accountingAccountName?: string;
  clientCode?: string;
  clientName?: string;
  salesRepresentativeCode?: string;
  salesRepresentativeName?: string;
  nfId?: string;
  nfNumber?: string;
  cfopCode?: string;
  cfopDescription?: string;
  currency?: string;
  value: number;
  payedValue: number;
  additionalValue: number;
  sensattaCreatedBy?: string;
  sensattaViewedBy?: string;
  sensattaApprovedBy?: string;
  sensattaLiquidatedBy?: string;
  observation?: string;

  constructor(data: AccountPayableSyncRequestInput) {
    Object.assign(this, {
      baseDate: data.DT_BASE,
      sensattaId: data.SEQUENCIAL_TITULO_PAGAR,
      key: data.CHAVE,
      companyCode: data.CODIGO_EMPRESA,
      paymentNumber: data.NUMERO_TITULO,
      issueDate: data.DATA_EMISSAO,
      dueDate: data.DATA_VENCIMENTO,
      liquidationDate: data.DATA_VENCIMENTO,
      status: data.SITUACAO,
      supplyCode: data.CODIGO_FORNECEDOR,
      supplyName: data.FORNECEDOR,
      recognitionTypeCode: data.CODIGO_TIPO_BAIXA,
      recognitionType: data.TIPO_BAIXA,
      accountingAccount: data.CONTA_CONTABIL,
      accountingClassification: data.CLASSIFICACAO_CONTABIL,
      accountingAccountName: data.NOME_CONTA_CONTABIL,
      clientCode: data.CODIGO_CLIENTE,
      clientName: data.CLIENTE,
      salesRepresentativeCode: data.CODIGO_REPRESENTANTE,
      salesRepresentativeName: data.REPRESENTANTE,
      nfId: data.SEQUENCIAL_NOTA_ENTRADA,
      nfNumber: data.NOTA_FISCAL,
      cfopCode: data.CODIGO_CFOP,
      cfopDescription: data.DESCRICAO_CFOP,
      currency: data.MOEDA,
      value: data.VALOR_BRUTO,
      payedValue: data.VALOR_PAGO,
      additionalValue: data.ACRESCIMO,
      sensattaCreatedBy: data.USUARIO_CRIACAO,
      sensattaViewedBy: data.USUARIO_VISTO,
      sensattaApprovedBy: data.USUARIO_APROVACAO,
      sensattaLiquidatedBy: data.USUARIO_LIQUIDACAO,
      observation: data.OBSERVACAO,
    });
  }
}
