import { StringUtils } from 'src/utils/string.utils';

export interface OrderLineSyncRequestInput {
  DATA_FATURAMENTO: Date;
  DATA_EMISSAO: Date;
  CODIGO_EMPRESA: string;
  EMPRESA: string;
  SEQUENCIAL_PEDIDO: string;
  SITUACAO: string;
  MERCADO: string;
  CODIGO_CLIENTE: string;
  CLIENTE: string;
  CODIGO_REPRESENTANTE: string;
  REPRESENTANTE: string;
  PRAZO: string;
  CATEGORIA_PEDIDO: string;
  CODIGO_LINHA: string;
  LINHA: string;
  CODIGO_PRODUTO: string;
  PRODUTO: string;
  QTD_PECAS: number;
  PESO_KG: number;
  MOEDA: string;
  VALOR_CUSTO: number;
  VALOR_DESCONTO_PROMOCAO: number;
  VALOR_VENDA_UN: number;
  VALOR_TABELA_UN: number;
  VALOR_TOTAL: number;
  VALOR_TITULO: number;
  SEQUENCIAL_TABELA_PRECO: string;
  TABELA_PRECO: string;
  SEQUENCIAL_TRANSPORTADORA: string;
  TRANSPORTADORA: string;
  DESCRICAO: string;
  SEQUENCIAL_TITULO_RECEBER: string;
  NUMERO_TITULO: string;
  CODIGO_GRUPO_EMPENHO: string;
  GRUPO_EMPENHO: string;
  CODIGO_EMPENHO: string;
  EMPENHO: string;
  OBSERVACAO: string;
  SEQUENCIAL_NOTA_SAIDA: string;
  NOTA_FISCAL: string;
  CODIGO_CFOP: string;
  DESCRICAO_CFOP: string;
}
export class OrderLineSyncRequestDto {
  billingDate?: Date;
  issueDate?: Date;
  companyCode?: string;
  companyName?: string;
  orderId?: string;
  situation?: string;
  market?: string;
  clientCode?: string;
  clientName?: string;
  salesRepresentativeCode?: string;
  salesRepresentativeName?: string;
  paymentTerm?: string;
  category?: string;
  productLineCode?: string;
  productLineName?: string;
  productCode?: string;
  productName?: string;
  quantity?: number;
  weightInKg?: number;
  currency?: string;
  costValue?: number;
  discountPromotionValue?: number;
  saleUnitValue?: number;
  referenceTableUnitValue?: number;
  totalValue?: number;
  receivableTitleValue?: number;
  referenceTableId?: string;
  referenceTableDescription?: string;
  freightCompanyId?: string;
  freightCompanyName?: string;
  description?: string;
  receivableTitleId?: string;
  receivableTitleNumber?: string;
  receivableTitleObservation?: string;
  accountGroupCode?: string;
  accountGroupName?: string;
  accountCode?: string;
  accountName?: string;
  nfId?: string;
  nfNumber?: string;
  cfopCode?: string;
  cfopDescription?: string;

  constructor(data: OrderLineSyncRequestInput) {
    Object.assign(this, {
      billingDate: data.DATA_FATURAMENTO,
      issueDate: data.DATA_EMISSAO,
      companyCode: data.CODIGO_EMPRESA,
      companyName: data.EMPRESA,
      orderId: data.SEQUENCIAL_PEDIDO,
      market: data.MERCADO,
      situation: data.SITUACAO,
      clientCode: data.CODIGO_CLIENTE,
      clientName: data.CLIENTE,
      salesRepresentativeCode: data.CODIGO_REPRESENTANTE,
      salesRepresentativeName: data.REPRESENTANTE,
      paymentTerm: data.PRAZO,
      category: data.CATEGORIA_PEDIDO,
      productLineCode: data.CODIGO_LINHA,
      productLineName: data.LINHA,
      productCode: data.CODIGO_PRODUTO,
      productName: data.PRODUTO,
      quantity: data.QTD_PECAS,
      weightInKg: data.PESO_KG,
      currency: data.MOEDA,
      costValue: data.VALOR_CUSTO,
      discountPromotionValue: data.VALOR_DESCONTO_PROMOCAO,
      saleUnitValue: data.VALOR_VENDA_UN,
      referenceTableUnitValue: data.VALOR_TABELA_UN,
      totalValue: data.VALOR_TOTAL,
      receivableTitleValue: data.VALOR_TITULO,
      referenceTableId: data.SEQUENCIAL_TABELA_PRECO,
      referenceTableDescription: data.TABELA_PRECO,
      freightCompanyId: data.SEQUENCIAL_TRANSPORTADORA,
      freightCompanyName: data.TRANSPORTADORA,
      description: data.DESCRICAO,
      receivableTitleId: data.SEQUENCIAL_TITULO_RECEBER,
      receivableTitleNumber: data.NUMERO_TITULO,
      receivableTitleObservation: data.OBSERVACAO,
      accountGroupCode: data.CODIGO_GRUPO_EMPENHO,
      accountGroupName: data.GRUPO_EMPENHO,
      accountCode: data.CODIGO_EMPENHO,
      accountName: data.EMPENHO,
      nfId: data.SEQUENCIAL_NOTA_SAIDA,
      nfNumber: data.NOTA_FISCAL,
      cfopCode: data.CODIGO_CFOP,
      cfopDescription: data.DESCRICAO_CFOP,
    });
  }
}
