export const FREIGHT_COMPANY_QUERY = /**sql */ `
SELECT
t.SEQUENCIAL_TRANSPORTADORA
,e.CODIGO_ENTIDADE
,e.NOME
,t.RAZAO_SOCIAL
,e.CPF_CNPJ
,t.INSCRICAO_ESTADUAL
,e.CEP
,e.BAIRRO
,e.endereco
,e.cidade
,e.uf
,e.e_mail
FROM SIGMA_VEN.TRANSPORTADORA t
LEFT JOIN SIGMA_VEN.ENTIDADE e ON t.ID_ENTIDADE  = e.CODIGO_ENTIDADE
`;
