export const INVENTORY_ITEM_TRACEABILITY_QUERY = `
SELECT 
   		  IP.ID_INVENTARIO,
 		    T.DATA_OPERACAO,
        T.NUMERO_CAIXA,
        L.PESO,
        L.TARA_CAIXA,
        T.OPERACAO,
        T.STATUS,
        T.LINHA_1,
        T.LINHA_2,
        T.LINHA_3,
        T.LINHA_4,
        T.LINHA_5,
        T.LINHA_6
FROM SIGMA_PCP.LOTE_ENTRADA L
JOIN SIGMA_PCP.INVENTARIO_CANCELADAS IC 
  ON L.ID_LOTE_ENTRADA = IC.ID_LOTE_ENTRADA
JOIN SIGMA_PCP.INVENTARIO_PRODUTO IP 
  ON IC.ID_INVENTARIO_PRODUTO = IP.ID_INVENTARIO_PRODUTO
JOIN SIGMA_VEN.PRODUTO P 
  ON P.SEQUENCIAL_PRODUTO = IP.SEQUENCIAL_PRODUTO
LEFT JOIN SIGMA_MAT.ALMOXARIFADO A 
  ON A.CODIGO_ALMOXARIFADO = L.CODIGO_ALMOXARIFADO
LEFT JOIN SIGMA_FIS.EMPRESA E 
  ON E.CODIGO_EMPRESA = A.CODIGO_EMPRESA
LEFT JOIN (
    SELECT 
    	L2.ID_LOTE_ENTRADA,
        L2.NUMERO_CAIXA,
        T2.DATA_OPERACAO,
        T2.OPERACAO,
        T2.STATUS,
        T2.LINHA_1,
        T2.LINHA_2,
        T2.LINHA_3,
        T2.LINHA_4,
        T2.LINHA_5,
        T2.LINHA_6
    FROM SIGMA_PCP.LOTE_ENTRADA L2,
         TABLE(sigma_pcp.pkg_consulta_etiqueta.ppl_etiqueta_detalhe(L2.NUMERO_CAIXA)) T2
) T 
  ON T.ID_LOTE_ENTRADA = L.ID_LOTE_ENTRADA
 WHERE IP.ID_INVENTARIO = :id_inventario
ORDER BY 
  	T.NUMERO_CAIXA,
	T.DATA_OPERACAO
`;
