export const INVENTORY_ITEM_QUERY = `
SELECT
	IP.ID_INVENTARIO,
	L.NUMERO_CAIXA,
	L.DATA_PRODUCAO,
	L.DATA_VALIDADE,
	P.SEQUENCIAL_PRODUTO,
	P.CODIGO_PRODUTO,
	TRIM(BOTH FROM REPLACE(REPLACE(P.DESCRICAO, CHR(10), ' '), CHR(13), ' ')) AS PRODUTO,
	L.CODIGO_SIF,
	L.PESO,
	L.TARA_CAIXA,
	L.USUARIO_CRIACAO
FROM
	SIGMA_PCP.LOTE_ENTRADA L,
	SIGMA_PCP.INVENTARIO_CANCELADAS IC,
	SIGMA_PCP.INVENTARIO_PRODUTO IP,
	SIGMA_PCP.INVENTARIO I,
	SIGMA_VEN.PRODUTO P,
	SIGMA_MAT.ALMOXARIFADO A,
	SIGMA_FIS.EMPRESA E
WHERE
	L.ID_LOTE_ENTRADA = IC.ID_LOTE_ENTRADA
	AND IC.ID_INVENTARIO_PRODUTO = IP.ID_INVENTARIO_PRODUTO
	AND P.SEQUENCIAL_PRODUTO = IP.SEQUENCIAL_PRODUTO
	AND I.ID_INVENTARIO = IP.ID_INVENTARIO
	AND A.CODIGO_ALMOXARIFADO = L.CODIGO_ALMOXARIFADO
	AND E.CODIGO_EMPRESA = A.CODIGO_EMPRESA
    AND I.ID_INVENTARIO IN (:id_inventarios)
ORDER BY
	L.DATA_PRODUCAO DESC
`;
